source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'
platform :ios,'9.0'
inhibit_all_warnings!
use_frameworks!

target 'KuBaoBei' do
    pod 'AFNetworking', '~> 3.0';
    pod 'BlocksKit';
    pod 'RDVTabBarController';
    pod 'AlicloudPush', '~> 1.9.8';
end
